In [1]:
import tensorflow as tf
import numpy as np

In [2]:
x1_data = [73, 93, 89, 96, 73]
x2_data = [80, 88, 91, 98, 66]
x3_data = [75, 93, 90, 100, 70]
y_data = [152, 185, 180, 196, 142]

In [3]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

In [4]:
w1 = tf.Variable(tf.random_normal([1]), name ='weight1')
w2 = tf.Variable(tf.random_normal([1]), name ='weight2')
w3 = tf.Variable(tf.random_normal([1]), name ='weight3')
b = tf.Variable(tf.random_normal([1]), name ='bias')

hypotheis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [5]:
cost = tf.reduce_mean(tf.square(hypotheis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [6]:
sess = tf.Session()

sess.run(tf.global_variables_initializer())

In [7]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost,hypotheis,train],
                                  feed_dict = {x1: x1_data, x2:x2_data, x3:x3_data, Y: y_data})
    if step % 100 == 0:
        print(step, cost_val, hy_val)

print("real Value : ", y_data)

0 38104.0 [-29.60425568 -18.50164032 -27.55365753 -24.60030365 -14.15426731]
100 21.6946 [ 143.7088623   189.50506592  177.55735779  198.73020935  144.45231628]
200 20.8447 [ 143.86572266  189.39872742  177.60691833  198.75444031  144.3225708 ]
300 20.0383 [ 144.01847839  189.29516602  177.6552124   198.777771    144.19644165]
400 19.273 [ 144.1672821   189.1942749   177.70228577  198.80023193  144.07383728]
500 18.5467 [ 144.31227112  189.09608459  177.74819946  198.82191467  143.95469666]
600 17.8575 [ 144.45347595  189.00042725  177.79295349  198.8427887   143.83889771]
700 17.2032 [ 144.59106445  188.9072876   177.83659363  198.862854    143.72634888]
800 16.582 [ 144.72511292  188.81658936  177.87915039  198.88220215  143.61698914]
900 15.9922 [ 144.85566711  188.72819519  177.92062378  198.90074158  143.51068115]
1000 15.4323 [ 144.98286438  188.64215088  177.96107483  198.91859436  143.40737915]
1100 14.9005 [ 145.10681152  188.55833435  178.00050354  198.93572998  143.30699158]

이런 방식은 data가 많아지면 너무 불편함 !!
좀 더 편하게 접근할 수 없을까? matrix 식으로 나타내보자

In [8]:
x_data = [[73,80,73], [93,88,93], [89,91,90], [96,98,100], [73,66,70]]
y_data = [[152],[185],[180],[196],[142]]
X = tf.placeholder(tf.float32, shape=[None,3]) # None = not determined
Y = tf.placeholder(tf.float32, shape=[None,1])

In [9]:
W = tf.Variable(tf.random_normal([3,1]), name = 'weight')
n = tf.Variable(tf.random_normal([1]), name = 'biase')

In [10]:
hypotheis = tf.matmul(X,W) + b 
# 순서 주의
cost = tf.reduce_mean(tf.square(hypotheis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [11]:
sess = tf.Session()

sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost,hypotheis,train],
                                  feed_dict = {X: x_data, Y: y_data})
    if step % 100 == 0:
        print(step, cost_val, hy_val)

print("real Value : ", y_data)

0 201519.0 [[-244.78848267]
 [-294.9598999 ]
 [-291.23120117]
 [-316.42364502]
 [-225.63670349]]
100 2.25716 [[ 150.56298828]
 [ 184.45077515]
 [ 181.13931274]
 [ 197.95539856]
 [ 140.05126953]]
200 2.23695 [[ 150.55484009]
 [ 184.4588623 ]
 [ 181.13574219]
 [ 197.94506836]
 [ 140.06861877]]
300 2.21716 [[ 150.54707336]
 [ 184.46669006]
 [ 181.13227844]
 [ 197.93484497]
 [ 140.08566284]]
400 2.19778 [[ 150.53965759]
 [ 184.47428894]
 [ 181.12892151]
 [ 197.92468262]
 [ 140.10235596]]
500 2.17881 [[ 150.53259277]
 [ 184.48164368]
 [ 181.12567139]
 [ 197.91461182]
 [ 140.11872864]]
600 2.1602 [[ 150.52587891]
 [ 184.48876953]
 [ 181.12249756]
 [ 197.90463257]
 [ 140.13479614]]
700 2.14196 [[ 150.51947021]
 [ 184.49568176]
 [ 181.11943054]
 [ 197.8946991 ]
 [ 140.15054321]]
800 2.12408 [[ 150.51341248]
 [ 184.50236511]
 [ 181.11647034]
 [ 197.88490295]
 [ 140.16603088]]
900 2.10652 [[ 150.50762939]
 [ 184.50883484]
 [ 181.11357117]
 [ 197.87512207]
 [ 140.18119812]]
1000 2.0893 [[ 150.502

## Lab 4-2 data from file

In [12]:
xy = np.loadtxt('DeepLearningZeroToAll/data-01-test-score.csv', delimiter= ',', dtype=np.float32)
print(xy)

[[  73.   80.   75.  152.]
 [  93.   88.   93.  185.]
 [  89.   91.   90.  180.]
 [  96.   98.  100.  196.]
 [  73.   66.   70.  142.]
 [  53.   46.   55.  101.]
 [  69.   74.   77.  149.]
 [  47.   56.   60.  115.]
 [  87.   79.   90.  175.]
 [  79.   70.   88.  164.]
 [  69.   70.   73.  141.]
 [  70.   65.   74.  141.]
 [  93.   95.   91.  184.]
 [  79.   80.   73.  152.]
 [  70.   73.   78.  148.]
 [  93.   89.   96.  192.]
 [  78.   75.   68.  147.]
 [  81.   90.   93.  183.]
 [  88.   92.   86.  177.]
 [  78.   83.   77.  159.]
 [  82.   86.   90.  177.]
 [  86.   82.   89.  175.]
 [  78.   83.   85.  175.]
 [  76.   83.   71.  149.]
 [  96.   93.   95.  192.]]


In [13]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# np slicing example

In [21]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("b\n",b)
print("b[:,1]\n",b[:,0])
print("b[-1]\n",b[-1])
print("b[-1, :]\n",b[-1, :])
print("b[-1, :-1]\n",b[-1, :-1])
print("b[0:2, :]\n",b[0:2, :])
print("b[1:,:-1]\n",b[1:,:-1])

b
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
b[:,1]
 [1 5 9]
b[-1]
 [ 9 10 11 12]
b[-1, :]
 [ 9 10 11 12]
b[-1, :-1]
 [ 9 10 11]
b[0:2, :]
 [[1 2 3 4]
 [5 6 7 8]]
b[1:,:-1]
 [[ 5  6  7]
 [ 9 10 11]]


In [15]:
print(x_data.shape, len(x_data))
print(y_data.shape, len(y_data))

(25, 3) 25
(25, 1) 25


In [16]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [17]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

print("real Value", y_data)
# Ask my score
print("Your score will be ", sess.run(
    hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ", sess.run(hypothesis,
                                        feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

0 Cost:  84.5557 
Prediction:
 [[ 144.25024414]
 [ 174.68516541]
 [ 171.17807007]
 [ 190.00410461]
 [ 130.5400238 ]
 [ 101.80138397]
 [ 147.09130859]
 [ 115.83628082]
 [ 167.87199402]
 [ 163.43962097]
 [ 138.42776489]
 [ 138.40560913]
 [ 173.23420715]
 [ 138.95362854]
 [ 148.34950256]
 [ 180.54263306]
 [ 128.39170837]
 [ 178.53540039]
 [ 164.38249207]
 [ 147.5645752 ]
 [ 171.45014954]
 [ 167.25398254]
 [ 162.33091736]
 [ 137.02482605]
 [ 179.17469788]]
100 Cost:  21.2548 
Prediction:
 [[ 151.75239563]
 [ 183.59329224]
 [ 180.01835632]
 [ 199.54794312]
 [ 137.37605286]
 [ 106.69898224]
 [ 154.14079285]
 [ 120.93362427]
 [ 176.06942749]
 [ 170.83714294]
 [ 145.27337646]
 [ 145.07528687]
 [ 182.45161438]
 [ 146.72880554]
 [ 155.40586853]
 [ 189.51231384]
 [ 135.86474609]
 [ 186.9677124 ]
 [ 173.20005798]
 [ 155.45069885]
 [ 179.73110962]
 [ 175.53594971]
 [ 170.25932312]
 [ 144.78471375]
 [ 188.46365356]]
200 Cost:  20.165 
Prediction:
 [[ 151.83891296]
 [ 183.59541321]
 [ 180.07958984]
 

2000 Cost:  9.99372 
Prediction:
 [[ 152.78465271]
 [ 183.74494934]
 [ 180.81921387]
 [ 199.32655334]
 [ 138.12239075]
 [ 105.43209839]
 [ 152.65209961]
 [ 118.01319885]
 [ 174.62101746]
 [ 166.97895813]
 [ 144.63783264]
 [ 143.54795837]
 [ 184.38223267]
 [ 149.82655334]
 [ 153.62641907]
 [ 188.72357178]
 [ 139.80589294]
 [ 184.74311829]
 [ 175.38233948]
 [ 157.32196045]
 [ 178.2191925 ]
 [ 174.67880249]
 [ 169.22213745]
 [ 148.39115906]
 [ 189.30871582]]
real Value [[ 152.]
 [ 185.]
 [ 180.]
 [ 196.]
 [ 142.]
 [ 101.]
 [ 149.]
 [ 115.]
 [ 175.]
 [ 164.]
 [ 141.]
 [ 141.]
 [ 184.]
 [ 152.]
 [ 148.]
 [ 192.]
 [ 147.]
 [ 183.]
 [ 177.]
 [ 159.]
 [ 177.]
 [ 175.]
 [ 175.]
 [ 149.]
 [ 192.]]
Your score will be  [[ 186.37509155]]
Other scores will be  [[ 199.64492798]
 [ 170.59326172]]


# Queue Reader

In [18]:
filename_queue = tf.train.string_input_producer(
    ['DeepLearningZeroToAll/data-01-test-score.csv'],shuffle = False, name ="filename_queue")

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

record_default = [[0],[0],[0],[0]]

xy = tf.decode_csv(value,record_defaults = record_default,field_delim=',')

In [19]:
train_x_batch , train_y_batch = \
    tf.train.batch([xy[0:-1],xy[-1:]],batch_size = 10)

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

In [20]:
# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(20001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 1000 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)

0 Cost:  6377.75 
Prediction:
 [[ 233.34191895]
 [ 273.02566528]
 [ 272.54614258]
 [ 299.18914795]
 [ 204.66009521]
 [ 154.13262939]
 [ 229.91603088]
 [ 178.89338684]
 [ 256.57098389]
 [ 242.52877808]]
1000 Cost:  18.5664 
Prediction:
 [[ 155.96282959]
 [ 181.73822021]
 [ 181.73764038]
 [ 200.02386475]
 [ 135.68519592]
 [ 103.0652771 ]
 [ 154.80580139]
 [ 121.92849731]
 [ 171.32571411]
 [ 163.13049316]]
2000 Cost:  13.3092 
Prediction:
 [[ 155.42654419]
 [ 182.44218445]
 [ 181.75357056]
 [ 199.83531189]
 [ 136.72650146]
 [ 103.67115784]
 [ 153.97848511]
 [ 120.31636047]
 [ 172.04393005]
 [ 163.45982361]]
3000 Cost:  10.0704 
Prediction:
 [[ 155.00837708]
 [ 182.99067688]
 [ 181.76579285]
 [ 199.68855286]
 [ 137.53752136]
 [ 104.14337921]
 [ 153.33424377]
 [ 119.06092834]
 [ 172.60391235]
 [ 163.71748352]]
4000 Cost:  8.06719 
Prediction:
 [[ 154.68240356]
 [ 183.41804504]
 [ 181.7752533 ]
 [ 199.57440186]
 [ 138.16918945]
 [ 104.51134491]
 [ 152.83258057]
 [ 118.08327484]
 [ 173.040496