## Tensor Manipulation

In [3]:
import tensorflow as tf
import numpy as np
import pprint as pp

## Sample Array

In [5]:
t = np.array([0,1,2,3,4,5,6])

pp.pprint(t)
print(t.ndim)
print(t.shape)
print(t[0],t[-1])
print(t[:2])

array([0, 1, 2, 3, 4, 5, 6])
1
(7,)
0 6
[0 1]


In [6]:
t = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
pp.pprint(t)
print(t.ndim)
print(t.shape)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])
2
(4, 3)


## Shape, Rank, Axis

In [13]:
sess = tf.InteractiveSession()

In [14]:
t = tf.constant([1,2,3,4])
tf.shape(t).eval()

array([4], dtype=int32)

In [16]:
t = tf.constant([[1,2],[3,4]])
tf.shape(t).eval()

array([2, 2], dtype=int32)

In [21]:
t = tf.constant([
    [
        [
            [1,2,3,4], 
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
])
pp.pprint([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval()

[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]


array([1, 2, 3, 4], dtype=int32)

## Matmul VS multiply

In [33]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
print("Matrix 1 shape", matrix1.shape)
print("Matrix 2 shape", matrix2.shape)
tf.matmul(matrix1, matrix2).eval()

Matrix 1 shape (1, 2)
Matrix 2 shape (2, 1)


array([[ 12.]], dtype=float32)

In [34]:
(matrix1*matrix2).eval() #element wise로 곱이 됨

array([[ 6.,  6.],
       [ 6.,  6.]], dtype=float32)

In [35]:
(matrix1 + matrix2).eval() #element wise로 덧셈이 됨
#Broadcasting 개념

array([[ 5.,  5.],
       [ 5.,  5.]], dtype=float32)

## Broadcasting

In [36]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
(matrix1+matrix2).eval()

array([[ 5.,  5.],
       [ 5.,  5.]], dtype=float32)

In [37]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1+matrix2).eval()

array([[ 5.,  5.]], dtype=float32)

## Random values for variable initializations 

In [39]:
tf.random_normal([3]).eval()

array([-0.69076681, -1.67468309,  0.17600335], dtype=float32)

In [40]:
tf.random_uniform([2]).eval()

array([ 0.48705792,  0.39994907], dtype=float32)

In [41]:
tf.random_uniform([2, 3]).eval()

array([[ 0.77905238,  0.23515677,  0.14727616],
       [ 0.92654574,  0.15224051,  0.94690883]], dtype=float32)

## Reduce Mean

In [43]:
tf.reduce_mean([1, 2], axis=0).eval()
#interger 여서 1.5 -> 1

1

In [44]:
tf.reduce_mean([1., 2.], axis=0).eval()

1.5

In [45]:
x = [[1.,2.],
    [3.,4.]]
tf.reduce_mean(x).eval()

2.5

In [46]:
tf.reduce_mean(x,axis=0).eval()

array([ 2.,  3.], dtype=float32)

In [47]:
tf.reduce_mean(x,axis=1).eval()

array([ 1.5,  3.5], dtype=float32)

In [48]:
tf.reduce_mean(x,axis=-1).eval()

array([ 1.5,  3.5], dtype=float32)

## reduce sum

In [49]:
tf.reduce_sum(x).eval()

10.0

In [50]:
tf.reduce_sum(x, axis=0).eval()

array([ 4.,  6.], dtype=float32)

In [51]:
tf.reduce_sum(x, axis=-1).eval()

array([ 3.,  7.], dtype=float32)

## argmax with axis

In [52]:
x = [[0, 1, 2],
     [2, 1, 0]]
tf.argmax(x, axis=0).eval()

array([1, 0, 0])

In [53]:
tf.argmax(x, axis=1).eval()

array([2, 0])

In [54]:
tf.argmax(x, axis=-1).eval()

array([2, 0])

## Reshape & Sqeeze & expand_dim

In [55]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [56]:
tf.reshape(t,shape=[-1,3]).eval()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [57]:
tf.reshape(t,shape=[-1,1,3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [59]:
tf.squeeze([[0], [1], [2]]).eval()

array([0, 1, 2], dtype=int32)

In [60]:
tf.expand_dims([0, 1, 2], 1).eval()

array([[0],
       [1],
       [2]], dtype=int32)

## one-hot

In [64]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval()

array([[[ 1.,  0.,  0.]],

       [[ 0.,  1.,  0.]],

       [[ 0.,  0.,  1.]],

       [[ 1.,  0.,  0.]]], dtype=float32)

In [65]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]], dtype=float32)

## Casting

In [66]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4], dtype=int32)

In [67]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

array([1, 0, 1, 0], dtype=int32)

## Stack

In [68]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [69]:
tf.stack([x, y, z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

## Ones like and Zeros like
같은 shape의 "1"로 구성된 array 이나 "0" 으로 구성된 array

In [70]:
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [71]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

## Zip

In [72]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [73]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
