In [1]:
import numpy as np

In [2]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("b\n",b)
print("b[:,1]\n",b[:,0])
print("b[-1]\n",b[-1])
print("b[-1, :]\n",b[-1, :])
print("b[-1, :-1]\n",b[-1, :-1])
print("b[0:2, :]\n",b[0:2, :])
print("b[1:,:-1]\n",b[1:,:-1])

b
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
b[:,1]
 [1 5 9]
b[-1]
 [ 9 10 11 12]
b[-1, :]
 [ 9 10 11 12]
b[-1, :-1]
 [ 9 10 11]
b[0:2, :]
 [[1 2 3 4]
 [5 6 7 8]]
b[1:,:-1]
 [[ 5  6  7]
 [ 9 10 11]]


In [7]:
b_std = np.array(
    [[1,2,3,4],
     [5,6,7,8],
     [9,10,11,12]])
b_std[:,0] = (b[:,0] - b[:,0].mean()) / b[:,0].std()
b_std

array([[-1,  2,  3,  4],
       [ 0,  6,  7,  8],
       [ 1, 10, 11, 12]])